name = "QFTFramework"
version = "0.1.0"
defaultTargets = ["QFTFramework"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "6dc31c12d6ffdc9a63ebddee67264ea348cc06f8"

[[lean_lib]]
name = "QFTFramework"
